package Acme::CPANAuthors::Japanese;

use strict;
use warnings;

our $VERSION = '0.071226';

use Acme::CPANAuthors::Register (
    AERDAN    => 'Kiyoshi Aman',
    AGREW     => 'Naoyuki Okumura',
    AHIROSE   => 'Akira HIROSE',
    AKIRA     => 'Akira Hangai',
    AKOBA     => 'Atsushi Kobayashi',
    AQL       => 'Tetsuya Toyoda',
    ARUTEIDO  => 'satoshi ishikawa',
    ASAKURA   => 'ASAKURA Takuji',
    ASARIH    => 'Hiro Asari',
    ASKADNA   => 'Shinichiro Aska',
    BANB      => 'ITO Nobuaki',
    BASHI     => 'Toshimasa Ishibashi',
    BAYSIDE   => 'Jun Shimizu',
    BOKUTIN   => 'Tomohiro Hosaka',
    BONAR     => 'Nakano Kyohei',
    BOXPHERE  => 'Satoshi Ohkubo',
    CHIBA     => 'Masahiro Chiba',
    COHTAN    => 'Kota Sakoda',
    DAIBA     => 'DAIBA, Keiichi',
    DANJOU    => 'Nobuo Danjou',
    DANKOGAI  => 'Dan Kogai',
    DGSCOPE   => 'Masayuki Komori',
    DMAKI     => 'Daisuke Maki',
    DRAWNBOY  => 'Hideaki Tanaka',
    FUJIMURA  => 'FUJIMURA Yuki',
    FUJIWARA  => 'Fujiwara Shunichiro',
    FUKUDA    => 'Keisuke Fukuda',
    GAOU      => 'Kazuharu Arakawa',
    GUNYA     => 'GUNYARA-KUN',
    HATA      => 'Masanori HATA',
    HAYASHI   => 'Hiroo HAYASHI',
    HEDWIG    => 'Yusuke Sugiyama',
    HIDE      => 'Hideo Kimura',
    HIGU      => 'Higuchi hiroyuki',
    HIKARINE  => 'Hajime Kurita',
    HIMAZU    => 'Hideyo Imazu',
    HIO       => 'YAMASHINA Hio',
    HIRATA    => 'HIRATA Yasuyuki',
    HIRO      => 'hiroshi kitano',
    HIROSE    => 'HIROSE Masaaki',
    HIROYUKI  => 'Hiroyuki Yamanaka',
    HIROYUKIM => 'Yamanaka Hiroyuki',
    HKOBA     => 'KOBAYASI, Hiroaki',
    HOLLY     => 'Akira Horimoto',
    HORIUCHI  => 'Yasuhiro Horiuchi',
    IHARA     => 'Ikuhiro IHARA',
    IKEBE     => 'IKEBE Tomohiro',
    IKEGAMI   => 'ikegami',
    IKUTA     => 'Masahito Ikuta',
    INA       => 'INABA Hitoshi',
    ISHIGAKI  => 'Kenichi Ishigaki',
    ISOYA     => 'Ryohei Isoya',
    ITWARRIOR => 'Hitoshi Amano',
    JIRO      => 'Jiro Nishiguchi',
    JKONDO    => 'Junya Kondo',
    JUNICHIRO => 'Junichiro Tobe',
    KAMO      => 'Yoshikazu Kamoshida',
    KAWABATA  => 'KAWABATA Kazumichi',
    KAWASAKI  => 'Kawasaki Yusuke',
    KAZEBURO  => 'Masahiro Nagano',
    KAZUHO    => 'Kazuho Oku',
    KEISUKE   => 'Keisuke Kuramata',
    KENJIRO   => 'Kenjiro Hirakawa',
    KENTARO   => 'Kentaro Kuribayashi',
    KIMURA    => 'Takeshi Kimura',
    KMIYAZAKI => 'Keitaro Miyazaki',
    KNAGANO   => 'Keiichiro Nagano',
    KNOK      => 'NOKUBI Takatsugu',
    KOBAYASI  => 'Hiroyuki Kobayasi',
    KOJUN     => 'Kojun Ueno',
    KOKOGIKO  => 'OHTSUKA Ko-hei',
    KONDO     => 'Yoshiyuki KONDO',
    KTAKATA   => 'Ken Takata',
    KTAT      => 'Kato Atsushi',
    KUBOTA    => 'Tomohiro KUBOTA',
    KUMA      => 'KUMAGAI Kentaro',
    KURIHARA  => 'Yoshiki KURIHARA',
    KWITKNR   => 'KAWAI, Takanori',
    KYANNY    => 'Kensuke Kaneko',
    KYO       => 'Kyo Nagashima',
    KZFM      => 'Kazufumi Ohkawa',
    KZTOMITA  => 'Kazuyoshi Tomita',
    LUSHE     => 'Masatoshi Mizuno',
    LYOKATO   => 'Lyo Kato',
    MAHITO    => 'Hogelist',
    MAIDO     => 'Masahiro Funakoshi',
    MAKAMAKA  => 'Makamaka Hannyaharamitu',
    MAKOTO    => 'Shin Honda',
    MASAHITO  => 'Masahito Yoshida',
    MASAKI    => 'NAKAGAWA Masaki',
    MASANORIH => 'Masanori Hara',
    MASAP     => 'Masahiro Funakoshi',
    MATTN     => 'Yasuhiro Matsumoto',
    MIKAGE    => 'SANO Taku',
    MIKI      => 'Takeshi Miki',
    MIKIHOSHI => 'KAN Fushihara',
    MIKIO     => 'Mikio Hirabayashi',
    MILANO    => 'Tsukui Akihiro',
    MINORU    => 'KAWAMOTO Minoru',
    MIYAGAWA  => 'Tatsuhiko Miyagawa',
    MIYAMUKO  => 'MIYAMUKO Katsuyuki',
    MIYAZAKI  => 'Ittetsu Miyazaki',
    MIZZY     => 'Gosuke Miyashita',
    MYUJI     => 'Yuji Maeda',
    NABESHIMA => 'Masaaki NABESHIMA',
    NANZOU    => 'Takaaki Mizuno',
    NAOYA     => 'Naoya Ito',
    NAOYAT    => 'Naoya "naochan" Tozuka',
    NAOYUKI   => 'Naoyuki Ito',
    NARUSE    => 'NARUSE, Yui',
    NEKOKAK   => 'Atsushi Kobayashi',
    NEZUMI    => 'IKEDA Soji',
    NISHIGAYA => 'NISHIGAYA, Yuki',
    NOZZZZZ   => 'Tetsunari Nozaki',
    NTSUTSUMI => 'Naoya Tsutsumi',
    NYARLA    => 'Naoki Okamura',
    OINUME    => 'Kazuhiro Oinuma',
    OUEST     => 'Daisuke NISHISAKA',
    OYAMA     => 'Hiroyuki OYAMA',
    OZAWA     => 'OZAWA Sakuro',
    PAINA     => 'SATO Taisuke',
    PEN       => 'Abe Masahiro',
    PIA       => 'Michiya Honda',
    QUEEN     => 'Yasuhiro Miyazaki',
    RINTARO   => 'Rintaro Ishizaki',
    RYOCHIN   => 'Okamoto RYO',
    SADAHIRO  => 'SADAHIRO Tomoyuki',
    SASAZUKA  => 'Seiji Sasazuka',
    SAYANO    => 'Satoru Yano',
    SEKIMURA  => 'Masayoshi Sekimura',
    SEYN      => 'Yasushi Nakajima',
    SHIBUYA   => 'Kazuhiro Shibuya',
    SHIGETA   => 'Takatsugu Shigeta',
    SHIGIO    => 'Shigio Yamaguchi',
    SHIKONO   => 'Shinji KONO',
    SHIMAZU   => 'Yuki SHIMAZU',
    SHINPEI   => 'HAYASHI, Shinpei',
    SHIRAIWA  => 'Kazuma Shiraiwa',
    SHOT      => 'Shota Takayama',
    SKONNO    => 'Satoshi Konno',
    SNGJOKEN  => 'Shingo Kikugawa',
    SUZUKI    => 'Yuji Suzuki',
    TAIY      => 'Taisuke Yamada',
    TAKASHI   => 'Takashi Saeki',
    TAKAYUKI  => 'Takayuki Ikeda',
    TAKEFUMI  => 'KIMURA, takefumi',
    TAKEO     => 'Takeo Suzuki',
    TAKERU    => 'Takeru INOUE',
    TAKESAKO  => 'Yoshinori TAKESAKO',
    TAKESHIGE => 'Ken Takeshige',
    TAKKYUN   => 'Takayuki Ikeda',
    TAMAKOTO  => 'Tanaka Makoto',
    TAMASHIRO => 'Yuji Tamashiro',
    TANIGUCHI => 'Koichi Taniguchi',
    TANIMOTO  => 'Satoshi Tanimoto',
    TARO      => 'Daisuke Komatsu',
    TAROK     => 'Taro Kawagishi',
    TATENO    => 'Yuichi Tateno',
    TAWAN     => 'Taro Funaki',
    TKURITA   => 'Tetsuro KURITA',
    TOCIYUKI  => 'MIZUTANI, Tociyuki',
    TOKUHIROM => 'MATSUNO Tokuhiro',
    TOMITA    => 'Naoki Tomita',
    TOMYHERO  => 'Tomohiro Teranishi',
    TOONA     => 'Naoto Ishikawa',
    TOPIA     => 'Tatuya Noda',
    TRAVAIL   => 'Tomoyuki SAWA',
    TSUKAMOTO => 'Makio Tsukamoto',
    TSUNODA   => 'TSUNODA Kazuya',
    TYANO     => 'Tatsuhiro YANO',
    TYPESTER  => 'Daisuke Murase',
    UMEMOTO   => 'Hajimu Umemoto',
    WATANABE  => 'WATANABE Hirofumi',
    XOR       => 'Izumi Kawashima',
    XCEZX     => 'Tsuyoshi Maekawa',
    YAMAMOTO  => 'Ryuzo Yamamoto',
    YAMATO    => 'Toshiyuki Yamato',
    YANA      => 'Toshimitu Yanagisawa',
    YANMAR    => 'Yamamoto Keiichiro',
    YAPPO     => 'Kazuhiro Osawa',
    YASU      => 'Yasushi Saito',
    YASUHIRO  => 'Yasuhiro Onishi',
    YOSHIDA   => 'Hironori Yoshida',
    YOSTY     => 'Koji Komatsu',
    YSAS      => 'Yasuhiro Sasama',
    YSUZUKI   => 'Yoshihiro SUZUKI',
    YUKINOBU  => 'NAGAYASU Yukinobu',
    YUPUG     => 'Yu Isobe',
    YUSUKE    => 'Yusuke Shibata',
    YUYAW     => 'Yuya Watanabe',
    ZIGOROU   => 'Toru Yamaguchi',
    ZIGUZAGU  => 'Hiroshi Sakai',
);

1;

__END__

=head1 NAME

Acme::CPANAuthors::Japanese - We are Japanese CPAN authors

=head1 DESCRIPTION

This class is used to provide a hash of Japanese CPAN author's Pause ID/name to Acme::CPANAuthors.

=head1 MAINTENANCE

If you are Japanese CPAN author not listed here, come CodeRepos to add your own id/name. If you are listed but are not Japanese (or just don't want to be listed), sorry to bother you but tell me via email, IRC, or RT. I'll remove.

=head1 SVN REPOSITORY

http://svn.coderepos.org/share/lang/perl/Acme-CPANAuthors-Japanese/

=head1 AUTHOR

Kenichi Ishigaki, E<lt>ishigaki at cpan.orgE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2007 by Kenichi Ishigaki.

This program is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

=cut
